# -*- coding: utf-8 -*-
"""
真实 BLK 炮镜文件基础特征分析器。

功能定位:
- 提取距离示数、自动抬炮、可变标尺范围等低成本特征。
- 从文件末尾提取低置信度来源注释。
- 不负责元数据 JSON 解析，不写入文件系统。
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any


class SightBlkAnalyzer:
    """真实 BLK 文件的自动特征提取工具。"""

    tail_read_bytes = 2048
    max_compatibility_scan_bytes = 4 * 1024 * 1024

    _bool_re_template = r"{key}\s*:\s*b\s*=\s*([A-Za-z0-9]+)"
    _distance_re = re.compile(r"distance\s*:\s*p3\s*=\s*([-+]?\d+(?:\.\d+)?)", re.IGNORECASE)
    _line_comment_re = re.compile(r"//(.*)")

    def analyze(self, file_path: str | Path) -> dict[str, Any]:
        """解析单个 BLK 文件特征。"""
        path = Path(file_path)
        content = self._read_text(path)
        distances = self._extract_distances(content)
        distance_declared = self._has_bool_declaration(content, "drawDistanceCorrection")
        apply_declared = self._has_bool_declaration(content, "applyCorrectionToGun")
        match_exp_class_status = self.check_match_exp_class(path)
        confidence, confidence_reasons = self._analysis_confidence(
            distance_declared,
            apply_declared,
            bool(distances),
            match_exp_class_status,
        )
        tail_comment = self.extract_tail_comment(path)
        return {
            "distance_correction": self._extract_bool(
                content,
                "drawDistanceCorrection",
                default=True,
            ),
            "apply_correction_to_gun": self._extract_bool(
                content,
                "applyCorrectionToGun",
                default=True,
            ),
            "has_variable_range": bool(distances),
            "range_min": min(distances) if distances else None,
            "range_max": max(distances) if distances else None,
            "suspected_mask": self._detect_suspected_mask(content),
            "match_exp_class_status": match_exp_class_status,
            "tail_comment": tail_comment,
            "tail_comment_confidence": self.classify_tail_comment(tail_comment),
            "confidence": confidence,
            "confidence_reasons": confidence_reasons,
        }

    def check_match_exp_class(self, file_path: str | Path) -> str:
        """最小化检查 matchExpClass 块，失败时只返回不可确认状态。"""
        path = Path(file_path)
        try:
            if path.stat().st_size > self.max_compatibility_scan_bytes:
                return "unknown_unreadable"
            raw = path.read_bytes()
        except OSError:
            return "unknown_unreadable"

        if self._looks_binary(raw):
            return "unknown_unreadable"
        try:
            content = self._decode_compatibility_bytes(raw)
            sanitized = self._sanitize_for_block_scan(content)
            match = re.search(r"\bmatchExpClass\b\s*\{", sanitized, flags=re.IGNORECASE)
            if not match:
                return "missing"
            opening_index = sanitized.find("{", match.start())
            closing_index = self._find_block_end(sanitized, opening_index)
            if closing_index < 0:
                return "unknown_unreadable"
            body = re.sub(r"[\s,;]+", "", sanitized[opening_index + 1:closing_index])
            return "present_with_entries" if body else "present_empty"
        except Exception:
            return "unknown_unreadable"

    def extract_tail_comment(self, file_path: str | Path) -> str | None:
        """用二进制 seek 读取 BLK 文件末尾，提取最后一条非空 // 注释。"""
        path = Path(file_path)
        try:
            with open(path, "rb") as f:
                f.seek(0, 2)
                size = f.tell()
                f.seek(max(0, size - self.tail_read_bytes))
                raw = f.read()
        except OSError:
            return None

        text = self._decode_tail_bytes(raw)
        if len(raw) == self.tail_read_bytes and "\n" in text:
            text = text.split("\n", 1)[1]

        comments = []
        for line in text.splitlines():
            match = self._line_comment_re.search(line)
            if not match:
                continue
            comment = match.group(1).strip()
            if comment:
                comments.append(comment)
        return comments[-1] if comments else None

    def classify_tail_comment(self, comment: str | None) -> str:
        """给尾部注释打低成本置信度标记。"""
        if not comment:
            return "unknown"
        normalized = comment.strip().lower()
        technical_tokens = (
            "eof",
            "end",
            "generated by",
            "do not edit",
            "auto generated",
        )
        if any(token in normalized for token in technical_tokens):
            return "technical_note"
        if re.search(r"[\u4e00-\u9fff]", comment):
            return "source_hint"
        if any(token in normalized for token in ("author", "by ", "made by", "created by")):
            return "source_hint"
        return "unknown"

    def batch_analyze(self, file_paths: list[Path], progress_callback=None) -> dict[str, dict[str, Any]]:
        """批量分析 BLK 文件，单文件失败不影响整批。"""
        results: dict[str, dict[str, Any]] = {}
        total = max(len(file_paths), 1)
        for index, file_path in enumerate(file_paths, start=1):
            try:
                results[str(file_path)] = self.analyze(file_path)
            except Exception as exc:
                results[str(file_path)] = {"error": str(exc)}
            if progress_callback:
                progress_callback(int(index / total * 100), str(file_path))
        return results

    def _read_text(self, path: Path) -> str:
        try:
            raw = path.read_bytes()
        except OSError:
            return ""
        for encoding in ("utf-8-sig", "gb18030", "latin-1"):
            try:
                return raw.decode(encoding)
            except UnicodeDecodeError:
                continue
        return raw.decode("utf-8", errors="ignore")

    @staticmethod
    def _looks_binary(raw: bytes) -> bool:
        if b"\x00" in raw:
            return True
        if not raw:
            return False
        control_count = sum(
            1
            for value in raw
            if value < 32 and value not in {9, 10, 13}
        )
        return control_count / len(raw) > 0.02

    @staticmethod
    def _decode_compatibility_bytes(raw: bytes) -> str:
        for encoding in ("utf-8-sig", "gb18030", "latin-1"):
            try:
                return raw.decode(encoding)
            except UnicodeDecodeError:
                continue
        raise UnicodeDecodeError("utf-8", raw, 0, len(raw), "unsupported text")

    @staticmethod
    def _sanitize_for_block_scan(content: str) -> str:
        result = list(content)
        state = "normal"
        quote = ""
        index = 0
        while index < len(content):
            char = content[index]
            next_char = content[index + 1] if index + 1 < len(content) else ""
            if state == "normal":
                if char == "/" and next_char == "/":
                    result[index] = result[index + 1] = " "
                    state = "line_comment"
                    index += 2
                    continue
                if char == "/" and next_char == "*":
                    result[index] = result[index + 1] = " "
                    state = "block_comment"
                    index += 2
                    continue
                if char in {'"', "'"}:
                    result[index] = " "
                    quote = char
                    state = "string"
                    index += 1
                    continue
            elif state == "line_comment":
                if char in {"\r", "\n"}:
                    state = "normal"
                else:
                    result[index] = " "
                index += 1
                continue
            elif state == "block_comment":
                result[index] = " "
                if char == "*" and next_char == "/":
                    result[index + 1] = " "
                    state = "normal"
                    index += 2
                    continue
                index += 1
                continue
            elif state == "string":
                result[index] = " "
                if char == "\\" and next_char:
                    result[index + 1] = " "
                    index += 2
                    continue
                if char == quote:
                    state = "normal"
                index += 1
                continue
            index += 1
        return "".join(result)

    @staticmethod
    def _find_block_end(content: str, opening_index: int) -> int:
        if opening_index < 0 or opening_index >= len(content) or content[opening_index] != "{":
            return -1
        depth = 0
        for index in range(opening_index, len(content)):
            if content[index] == "{":
                depth += 1
            elif content[index] == "}":
                depth -= 1
                if depth == 0:
                    return index
        return -1

    def _decode_tail_bytes(self, raw: bytes) -> str:
        for encoding in ("utf-8-sig", "gb18030", "latin-1"):
            try:
                return raw.decode(encoding, errors="ignore")
            except UnicodeDecodeError:
                continue
        return raw.decode("utf-8", errors="ignore")

    def _extract_bool(self, content: str, key: str, default: bool | None = None) -> bool | None:
        pattern = re.compile(self._bool_re_template.format(key=re.escape(key)), re.IGNORECASE)
        match = pattern.search(content)
        if not match:
            return default
        value = match.group(1).strip().lower()
        if value in {"yes", "true", "1"}:
            return True
        if value in {"no", "false", "0"}:
            return False
        return default

    def _has_bool_declaration(self, content: str, key: str) -> bool:
        pattern = re.compile(self._bool_re_template.format(key=re.escape(key)), re.IGNORECASE)
        return pattern.search(content) is not None

    @staticmethod
    def _analysis_confidence(
        distance_declared: bool,
        apply_declared: bool,
        has_variable_range: bool,
        match_exp_class_status: str,
    ) -> tuple[str, list[str]]:
        reasons: list[str] = []
        if not distance_declared:
            reasons.append("distance_correction_defaulted")
        if not apply_declared:
            reasons.append("apply_correction_to_gun_defaulted")
        if match_exp_class_status == "unknown_unreadable":
            reasons.append("compatibility_unreadable")

        has_explicit_features = distance_declared or apply_declared or has_variable_range
        if not has_explicit_features:
            reasons.append("no_explicit_features")

        compatibility_readable = match_exp_class_status != "unknown_unreadable"
        if distance_declared and apply_declared and compatibility_readable:
            return "high", reasons
        if has_explicit_features and compatibility_readable:
            return "medium", reasons
        return "low", reasons

    def _extract_distances(self, content: str) -> list[int]:
        distances: list[int] = []
        for match in self._distance_re.finditer(content):
            try:
                distances.append(int(float(match.group(1))))
            except ValueError:
                continue
        return distances

    def _detect_suspected_mask(self, content: str) -> bool:
        if "drawCircles" not in content and "draw_circles" not in content:
            return False
        diameter_matches = re.findall(r"diameter\s*:\s*f\s*=\s*([-+]?\d+(?:\.\d+)?)", content, flags=re.IGNORECASE)
        size_matches = re.findall(r"size\s*:\s*f\s*=\s*([-+]?\d+(?:\.\d+)?)", content, flags=re.IGNORECASE)
        values = []
        for raw in diameter_matches + size_matches:
            try:
                values.append(float(raw))
            except ValueError:
                continue
        return any(value >= 1.0 for value in values)
